version: "3.9"

services:
  mysql:
    image: mysql:8.4
    container_name: gestion-planos-tecnicos-mysql-1
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=TuPassFuerte123
      - MYSQL_DATABASE=appdb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  adminer:
    image: adminer:latest
    container_name: gestion-planos-tecnicos-adminer-1
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - "8080:8080"

volumes:
  mysql_data:
